###

PUT http://localhost:3000/user/6974d77bb9d6f59b625eede6
Content-Type: application/json

{
  "email": "example@gmail.com",
  "username": "exmaple_user",
  "password": "secret_password"
}

###

GET http://localhost:3000/user/697a78c9437f1b91bae9a42d

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "newuser@example.com",
    "username": "newuser",
    "password": "newpassword"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "username": "newuser",
    "password": "newpassword"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlhMDA2M2M3M2I0NWIxOGNlNzQwMWUiLCJpYXQiOjE3NzE3MDAzMjMsImV4cCI6MTc3MTc4NjcyM30.tKLmxlWy2QHmvu_rqQfWg3LS1nWkEzAKUkNLXF4XplI"
}

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTlhMDA2M2M3M2I0NWIxOGNlNzQwMWUiLCJpYXQiOjE3NzE3MDE1NjEsImV4cCI6MTc3MTc4Nzk2MX0.nuRQr0QiChim3bgUIIDnlxsrRdu1NTjw3FXubOZhwog
