import {DEFAULT_JWT_EXPIRATION_TIME_SECONDS, DEFAULT_REFRESH_JWT_EXPIRATION_TIME_SECONDS} from "./consts";

export const jwtExpirationTimeInSeconds = () => process.env.JWT_EXPIRATION_TIME_SECONDS ? +process.env.JWT_EXPIRATION_TIME_SECONDS : DEFAULT_JWT_EXPIRATION_TIME_SECONDS

export const refreshJwtExpirationTimeInSeconds = () => process.env.REFRESH_JWT_EXPIRATION_TIME_SECONDS ? +process.env.REFRESH_JWT_EXPIRATION_TIME_SECONDS : DEFAULT_REFRESH_JWT_EXPIRATION_TIME_SECONDS